### ISSUE TITLE
Unhijack node doesn't work

### ISSUE THREAD

**Issue by codecomputation** [chrisgoringe/cg-noise#16] opened 2023-11-09 19:12 UTC
Unhijack noise node doesn't work. Noise remains even after adding the Unhijack node. You can reproduce this by creatiing an image without the hijack and unhijack nodes, create a 2nd image with both nodes, then load the first image and trying to recreate it again. A different image would be produced.

**Comment by chrisgoringe** [comment] 2023-11-10 01:16
Can't reproduce - possibly fixed in passing in 1.1.

|Initial|With Hijack|After Hijack removed|
|-|-|-|
|![initial](https://github.com/chrisgoringe/cg-noise/assets/4371971/29e8a941-9b15-4343-bf82-ee5a3aa82efb)|![hijacked](https://github.com/chrisgoringe/cg-noise/assets/4371971/2efd6826-0146-4af7-b917-f06a88dc55dd)|![unhijacked](https://github.com/chrisgoringe/cg-noise/assets/4371971/d2a00a8c-c49a-407f-b0f2-3159aa9af348)|

**Closed as completed by chrisgoringe** 2023-11-10 01:16 UTC
